import { OTHER_VALUE } from '@/domain/devices';
import { type DemoProject, evenShares } from './demo-catalog';
import { type DemoVisit, request } from './demo-visits';

const DOCS_VISITS: readonly DemoVisit[] = [
  {
    sessionId: 'e5a1c9d2-7b3f-4e60-8a14-2c9d0f6b7a01',
    daysAgo: 1,
    startHour: 10,
    startMinute: 20,
    deviceType: 'desktop',
    browser: 'firefox',
    os: 'linux',
    country: 'PT',
    channel: 'organic',
    events: [
      { second: 2, name: 'page_view', path: '/' },
      { second: 25, name: 'page_view', path: '/docs/:slug' },
      {
        second: 80,
        name: 'code_copied',
        path: '/docs/:slug',
        properties: { language: 'typescript' },
      },
      { second: 140, name: 'page_view', path: '/api/:section' },
      {
        second: 171,
        name: 'code_copied',
        path: '/api/:section',
        properties: { language: 'shell' },
      },
    ],
  },
  {
    sessionId: 'f6b2d0e3-8c4a-4f71-9b25-3d0e1a7c8b02',
    daysAgo: 2,
    startHour: 16,
    startMinute: 45,
    deviceType: 'mobile',
    browser: 'chrome',
    os: 'android',
    country: 'BR',
    channel: 'referral',
    events: [
      { second: 3, name: 'page_view', path: '/guides/:slug' },
      {
        second: 40,
        name: 'version_switched',
        path: '/guides/:slug',
        properties: { version: 'v1' },
      },
      request(61, '/guides/:slug', {
        method: 'POST',
        route: '/feedback',
        status: 201,
        durationMs: 118,
      }),
      { second: 61, name: 'feedback_sent', path: '/guides/:slug', properties: { helpful: true } },
    ],
  },
  {
    sessionId: '07c3e1f4-9d5b-4a82-8c36-4e1f2b8d9c03',
    daysAgo: 3,
    startHour: 9,
    startMinute: 5,
    deviceType: 'desktop',
    browser: 'chrome',
    os: 'windows',
    country: 'ES',
    channel: 'direct',
    events: [
      { second: 1, name: 'page_view', path: '/search' },
      { second: 12, name: 'search_performed', path: '/search', properties: { results: 'none' } },
      { second: 30, name: 'search_performed', path: '/search', properties: { results: 'some' } },
      { second: 34, name: 'page_view', path: '/docs/:slug' },
      { second: 120, name: 'page_view', path: '/changelog' },
      request(150, '/changelog', {
        method: 'POST',
        route: '/newsletter',
        status: 201,
        durationMs: 214,
      }),
      { second: 150, name: 'newsletter_subscribed', path: '/changelog' },
    ],
  },
];

export const DEMO_DOCS: DemoProject = {
  id: '0c9b8a7d-6e5f-4a3b-8c2d-1e0f9a8b7c6d',
  name: 'Demo Docs',
  timezone: 'Europe/Lisbon',
  conversionEvent: null,
  visitsPerPageView: 0.38,
  identifiedShare: 0,
  pages: [
    { path: '/docs/:slug', perDay: 120, visitsPerView: 0.42 },
    { path: '/', perDay: 40, visitsPerView: 0.9 },
    { path: '/guides/:slug', perDay: 35, visitsPerView: 0.55 },
    { path: '/api/:section', perDay: 30, visitsPerView: 0.4 },
    { path: '/search', perDay: 22, visitsPerView: 0.7 },
    { path: '/changelog', perDay: 10, visitsPerView: 0.85 },
    { path: '/status', perDay: 4, visitsPerView: 0.95 },
  ],
  events: [
    {
      name: 'code_copied',
      perDay: 40,
      visitsPerCount: 0.35,
      properties: [
        {
          key: 'language',
          carriedShare: 1,
          values: [
            ['typescript', 0.46],
            ['javascript', 0.28],
            ['shell', 0.17],
            ['python', 0.09],
          ],
        },
      ],
    },
    {
      name: 'search_performed',
      perDay: 26,
      visitsPerCount: 0.62,
      properties: [
        {
          key: 'results',
          carriedShare: 1,
          values: [
            ['some', 0.81],
            ['none', 0.19],
          ],
        },
      ],
    },
    {
      name: 'feedback_sent',
      perDay: 6,
      visitsPerCount: 0.97,
      properties: [
        {
          key: 'helpful',
          carriedShare: 1,
          values: [
            ['true', 0.72],
            ['false', 0.28],
          ],
        },
      ],
    },
    {
      name: 'version_switched',
      perDay: 5,
      visitsPerCount: 0.9,
      properties: [
        {
          key: 'version',
          carriedShare: 1,
          values: [
            ['v2', 0.8],
            ['v1', 0.2],
          ],
        },
      ],
    },
    { name: 'newsletter_subscribed', perDay: 1.5, visitsPerCount: 1, properties: [] },
  ],
  routes: [
    {
      method: 'POST',
      route: '/feedback',
      perDay: 6,
      successStatus: 201,
      failures: [[429, 0.02]],
      medianDurationMs: 120,
      screens: [
        ['/docs/:slug', 0.6],
        ['/guides/:slug', 0.4],
      ],
    },
    {
      method: 'POST',
      route: '/newsletter',
      perDay: 1.5,
      successStatus: 201,
      failures: [[422, 0.05]],
      medianDurationMs: 210,
      screens: [
        ['/changelog', 0.55],
        ['/', 0.45],
      ],
    },
  ],
  deviceTypes: evenShares([
    ['desktop', 0.71],
    ['mobile', 0.26],
    ['tablet', 0.03],
  ]),
  browsers: evenShares([
    ['chrome', 0.58],
    ['firefox', 0.14],
    ['safari', 0.13],
    ['edge', 0.1],
    ['opera', 0.03],
    [OTHER_VALUE, 0.02],
  ]),
  operatingSystems: evenShares([
    ['windows', 0.38],
    ['macos', 0.3],
    ['linux', 0.14],
    ['android', 0.1],
    ['ios', 0.06],
    [OTHER_VALUE, 0.02],
  ]),
  countries: evenShares([
    ['PT', 0.41],
    ['BR', 0.22],
    ['ES', 0.12],
    ['US', 0.09],
    ['DE', 0.05],
    [OTHER_VALUE, 0.11],
  ]),
  channels: {
    paid: 0,
    email: 0,
    social: 0.06,
    campaign: 0,
    organic: 0.52,
    referral: 0.2,
    direct: 0.22,
  },
  sources: [
    {
      source: 'www.google.com',
      medium: null,
      channel: 'organic',
      share: 0.85,
      conversionWeight: 1,
      adClickShare: 0,
    },
    {
      source: 'duckduckgo.com',
      medium: null,
      channel: 'organic',
      share: 0.15,
      conversionWeight: 1,
      adClickShare: 0,
    },
    {
      source: 'github.com',
      medium: null,
      channel: 'referral',
      share: 0.7,
      conversionWeight: 1,
      adClickShare: 0,
    },
    {
      source: 'stackoverflow.com',
      medium: null,
      channel: 'referral',
      share: 0.3,
      conversionWeight: 1,
      adClickShare: 0,
    },
    {
      source: '(direct)',
      medium: null,
      channel: 'direct',
      share: 1,
      conversionWeight: 1,
      adClickShare: 0,
    },
    {
      source: 'www.linkedin.com',
      medium: null,
      channel: 'social',
      share: 1,
      conversionWeight: 1,
      adClickShare: 0,
    },
  ],
  exampleFunnel: [
    { type: 'page', path: '/search' },
    { type: 'event', name: 'search_performed' },
    { type: 'page', path: '/docs/:slug' },
    { type: 'event', name: 'code_copied' },
  ],
  funnelContinuation: [0.9, 0.55, 0.4],
  person: null,
  visits: DOCS_VISITS,
};
